import { profileImageSrc } from "@/lib/profile-images";

export const communityPosts = [
  {
    id: "1",
    user: "@scentlover_jp",
    tag: "#floral",
    text: "Creed Aventus actually works for me in July heat. Essense flagged the timing.",
    likes: 18,
    comments: 8,
    shares: 3,
    formula: true,
    avatarSrc: profileImageSrc.maleJapan,
  },
  {
    id: "2",
    user: "@perfumegeek",
    tag: "#woody",
    text: "Weather-aware dosing is real. Hot day + Acqua di Gio = disaster. Essense moved me to Tom Ford Oud Wood and I've never gotten so many compliments.",
    likes: 31,
    comments: 12,
    shares: 5,
    formula: false,
    avatarSrc: profileImageSrc.maleChinese,
  },
  {
    id: "3",
    user: "@monicaw",
    tag: "#oriental",
    text: "Mia talked me into a base-heavy formula before an evening meeting. Worked.",
    likes: 22,
    comments: 6,
    shares: 2,
    formula: true,
    avatarSrc: profileImageSrc.femaleLatino,
  },
  {
    id: "4",
    user: "@fragrancemaven",
    tag: "#floral",
    text: "Apparently I wear florals in spring and orientals in winter. Didn't notice until the journal showed me.",
    likes: 44,
    comments: 15,
    shares: 7,
    formula: false,
    avatarSrc: profileImageSrc.femaleFilipino,
  },
  {
    id: "5",
    user: "@urbanscent",
    tag: "#fresh",
    text: "The scan picks up stress conductance. I test higher on Mondays, which tracks.",
    likes: 27,
    comments: 9,
    shares: 4,
    formula: false,
    avatarSrc: profileImageSrc.maleWhite,
  },
  {
    id: "6",
    user: "@essensefan_sg",
    tag: "#woody",
    text: "Join the Essense Club. I'm at 340 points. Almost at Gold tier.",
    likes: 19,
    comments: 4,
    shares: 1,
    formula: false,
    avatarSrc: profileImageSrc.maleChinese,
  },
];

export const suggestedUsers = [
  {
    name: "Kenji Yamamoto",
    tag: "Tokyo · fresh florals",
    imageSrc: profileImageSrc.maleJapan,
  },
  {
    name: "Wei Zhang",
    tag: "Shanghai · woody blends",
    imageSrc: profileImageSrc.maleChinese,
  },
  {
    name: "Sofia Ruiz",
    tag: "Citrus curator",
    imageSrc: profileImageSrc.femaleLatino,
  },
  {
    name: "Ana Reyes",
    tag: "Manila · layering coach",
    imageSrc: profileImageSrc.femaleFilipino,
  },
  {
    name: "Lukas Berg",
    tag: "Nordic minimalist",
    imageSrc: profileImageSrc.maleWhite,
  },
];
